const request = require('../util/request');
const validator = require('../util/validator')
const apiConstants = require('../constants/apiConstants')


/**
 * Payload for the FCM messaging operation.
 * @typedef {Object} BaseMessage
 * @property {Object.<string, string>} [data] - Key-value pairs to be included in the message payload.
 * @property {Notification} [notification] - Notification to be included in the message.
 * @property {AndroidConfig} [android] - Android-specific options for handling the message.
 * @property {WebpushConfig} [webpush] - Webpush-specific options for handling the message.
 * @property {ApnsConfig} [apns] - APNs (Apple Push Notification service) specific options for handling the message.
 * @property {FcmOptions} [fcmOptions] - Options for customizing the behavior of the FCM message.
 */

/**
 * Response object for managing messaging topics.
 * @typedef {Object} MessagingTopicManagementResponse
 * @property {number} failureCount - The number of registration tokens that could not be subscribed to the topic and resulted in an error.
 * @property {number} successCount - The number of registration tokens that were successfully subscribed to the topic.
 * @property {FirebaseArrayIndexError[]} errors - An array of errors corresponding to the provided registration token(s). The length of this array will be equal to `failureCount`.
 */

/**
 * Payload for sending messages to a specific device token.
 * @typedef {BaseMessage} TokenMessage
 * @property {string} token - Device token to which the message will be sent.
 */

/**
 * Payload for sending messages to a specific topic.
 * @typedef {BaseMessage} TopicMessage
 * @property {string} topic - Topic to which the message will be sent.
 */

/**
 * Payload for sending messages to devices that match a condition.
 * @typedef {BaseMessage} ConditionMessage
 * @property {string} condition - Condition to be met by the devices to receive the message.
 */

/**
 * Payload for sending messages via FCM.
 * The payload contains all the fields in the BaseMessage type, and exactly one of token, topic, or condition.
 * {@link https://github.com/firebase/firebase-admin-node/blob/837b69b61b3df3dcd8a31ccd16062e1bba236dca/src/messaging/messaging-api.ts#L45 | Message}
 * @typedef {TokenMessage | TopicMessage | ConditionMessage} Message
 */


/**
 * Payload for sending multicast messages via FCM.
 * Multicast messages are sent to multiple device tokens simultaneously.
 * {@link https://github.com/firebase/firebase-admin-node/blob/837b69b61b3df3dcd8a31ccd16062e1bba236dca/src/messaging/messaging-api.ts#L51 | MulticastMessage}
 * @typedef {BaseMessage} MulticastMessage
 * @property {string[]} tokens - Array of device tokens to which the message will be sent.
 *                               The message will be delivered to all devices specified in this array.
 */

// https://github.com/firebase/firebase-admin-node/blob/837b69b61b3df3dcd8a31ccd16062e1bba236dca/src/messaging/messaging-api.ts#L51
function getUrlPath(projectId) {
  return `/v1/projects/${projectId}/messages:send`
}

/**
 * Sends the given message via FCM.
 *
 * @param projectId - projectId assigned in firebase
 * @param accessToken - Access token generated by google jwt.
 * @param {Message} message - The message payload.
 * @param dryRun - Whether to send the message in the dry-run
 *   (validation only) mode.
 * @returns A promise fulfilled with a unique message ID
 *   string after the message has been successfully handed off to the FCM
 *   service for delivery.
 */
function send(projectId, accessToken, message, dryRun) {
  const urlPath = getUrlPath(projectId);
  const data = { message };
  if (dryRun) {
    data.validate_only = true;
  }
  return request.sendRequestWithErrorCheck(apiConstants.FCM.SEND_HOST, urlPath, apiConstants.HTTP_METHOD.POST, accessToken, data);
}

/**
* Sends each message in the given array via Firebase Cloud Messaging.
*
* The responses list obtained from the return value corresponds to the order of `messages`.
* An error from this method or a `BatchResponse` with all failures indicates a total failure,
* meaning that none of the messages in the list could be sent. Partial failures or no
* failures are only indicated by a `BatchResponse` return value.
*
* @param {string} projectId - projectId assigned in firebase
* @param {string} accessToken - Access token generated by google jwt.
* @param {Message} messages - A non-empty array
*   containing up to 500 messages.
* @param {Boolean} dryRun - Whether to send the messages in the dry-run
*   (validation only) mode.
* @returns {Promise<{success: string, data: string, message: string}>}A Promise fulfilled with an object representing the result of the
*   send operation.
*/
function sendEach(projectId, accessToken, messages, dryRun) {
  const urlPath = getUrlPath(projectId);
  const requests = messages.map((message) => {
    const data = { message };
    if (dryRun) {
      data.validate_only = true;
    }
    return request.sendRequestForSendResponse(apiConstants.FCM.SEND_HOST, urlPath, apiConstants.HTTP_METHOD.POST, accessToken, data);
  });
  
  return Promise.all(requests)
    .then((responses) => {
      const successCount = responses.filter((resp) => resp.success).length;
      const failureCount = responses.length - successCount;
      return {
        responses,
        successCount,
        failureCount,
      };
    })
    .catch((error) => {
      console.error('Error sending FCM messages:', error);
      // If an error occurs while sending messages, return an empty response array
      return {
        responses: [],
        successCount: 0,
        failureCount: messages.length,
      };
    });
}

/**
 * Sends the given multicast message to all the FCM registration tokens
 * specified in it.
 *
 * This method uses the {@link sendEach} API under the hood to send the given
 * message to all the target recipients. The responses list obtained from the
 * return value corresponds to the order of tokens in the `MulticastMessage`.
 * An error from this method or a `BatchResponse` with all failures indicates a total
 * failure, meaning that the messages in the list could be sent. Partial failures or
 * failures are only indicated by a `BatchResponse` return value.
 *
 * @param {string} projectId - projectId assigned in firebase
 * @param {string} accessToken - Access token generated by google jwt.
 * @param {MulticastMessage} message - A multicast message
 *   containing up to 500 tokens.
 * @param {Boolean} dryRun - Whether to send the message in the dry-run
 *   (validation only) mode.
 * @returns {Promise<BatchResponse>}A Promise fulfilled with an object representing the result of the
 *   send operation.
 */
function sendEachForMulticast(projectId, accessToken, message, dryRun) {
  const messages = message.tokens.map((token) => {
    return {
      token,
      android: message.android,
      apns: message.apns,
      data: message.data,
      notification: message.notification,
      webpush: message.webpush,
      fcmOptions: message.fcmOptions,
    };
  });
  return sendEach(projectId, accessToken, messages, dryRun);
}

/**
 * Helper method which sends and handles topic subscription management requests.
 * @param {string} accessToken - Access token generated by google jwt.
 * @param {string[] | string} registrationTokenOrTokens - The registration token or an array of
 *     registration tokens to unsubscribe from the topic.
 * @param {string} topic - The topic to which to subscribe.
 * @param {string} path - The endpoint path to use for the request.
 *
 * @returns A Promise fulfilled with the parsed server
 *   response.
 */
function sendTopicManagementRequest(accessToken, registrationTokenOrTokens, topic, path) {
  let registrationTokensArray = registrationTokenOrTokens;
  if(validator.isString(registrationTokenOrTokens)) {
    registrationTokensArray = [registrationTokenOrTokens];
  }
  const data = {
    to: topic,
    registration_tokens: registrationTokensArray,
  };
  return request.sendRequestWithErrorCheck(apiConstants.FCM.TOPIC_MANAGEMENT_HOST, path, apiConstants.HTTP_METHOD.POST, accessToken, data);
}

/**
 * Subscribes a device to an FCM topic.
 *
 * See {@link https://firebase.google.com/docs/cloud-messaging/manage-topics#suscribe_and_unsubscribe_using_the |
* Subscribe to a topic}
* for code samples and detailed documentation. Optionally, you can provide an
* array of tokens to subscribe multiple devices.
*
* @param {string} accessToken - Access token generated by google jwt.
* @param {string[] | string} registrationTokenOrTokens - A token or array of registration tokens
*   for the devices to subscribe to the topic.
* @param {string} topic - The topic to which to subscribe.
*
* @returns {Promise<MessagingTopicManagementResponse>} A promise fulfilled with the server's response after the device has been
*   subscribed to the topic.
*/
function subscribeToTopic(accessToken, registrationTokenOrTokens, topic) {
  const path = apiConstants.FCM.TOPIC_MANAGEMENT_ADD_PATH;
  return sendTopicManagementRequest(accessToken, registrationTokenOrTokens, topic, path);
}

/**
* Unsubscribes a device from an FCM topic.
*
* See {@link https://firebase.google.com/docs/cloud-messaging/admin/manage-topic-subscriptions#unsubscribe_from_a_topic |
* Unsubscribe from a topic}
* for code samples and detailed documentation.  Optionally, you can provide an
* array of tokens to unsubscribe multiple devices.
*
* @param {string} accessToken - Access token generated by google jwt.
* @param {string[]} registrationTokenOrTokens - A device registration token or an array of
*   device registration tokens to unsubscribe from the topic.
* @param {string} topic - The topic from which to unsubscribe.
*
* @returns {Promise<MessagingTopicManagementResponse>} A promise fulfilled with the server's response after the device has been
*   unsubscribed from the topic.
*/
function unsubscribeFromTopic(accessToken, registrationTokenOrTokens, topic) {
  const path = apiConstants.FCM.TOPIC_MANAGEMENT_REMOVE_PATH;
  return sendTopicManagementRequest(accessToken, registrationTokenOrTokens, topic, path);

}

module.exports = {
  subscribeToTopic,
  unsubscribeFromTopic,
  send,
  sendEachForMulticast,
  sendEach,
}